# Generated by Django 4.1 on 2022-08-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Ad:')),
                ('last_name', models.CharField(max_length=30, verbose_name='Soyad:')),
                ('number', models.IntegerField(verbose_name='Numara:')),
                ('description', models.TextField(blank=True, null=True)),
                ('register_date', models.DateField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
